// src/lib/components/Gallery.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import gsap from 'gsap';
  import { fade, scale } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';

  const placeholderImages = [
    "https://images.unsplash.com/photo-1544148103-0773bf10d330?q=80&w=2070&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=1974&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=2070&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=2070&auto=format&fit=crop"
  ];

  let containerRef: HTMLElement;
  let selectedImg: string | null = $state(null);

  onMount(() => {
    const images = gsap.utils.toArray('.gallery-item');
    images.forEach((img: any) => {
      gsap.from(img, {
        scrollTrigger: {
          trigger: img,
          start: "top 85%",
          end: "top 50%",
          scrub: 1,
        },
        y: 50,
        opacity: 0,
        scale: 0.95,
        duration: 1,
        ease: "power2.out",
      });
    });
  });

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') selectedImg = null;
  }
</script>

<svelte:window on:keydown={handleKeydown} />

<section bind:this={containerRef} class="py-32 px-8 md:px-24 bg-secondary">
  <div class="max-w-6xl mx-auto">
    <h2 class="text-sm tracking-[0.3em] uppercase text-accent mb-16 text-center">Visual Diary</h2>
    
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      {#each placeholderImages as src}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="gallery-item cursor-pointer overflow-hidden aspect-[4/3] relative group"
          onclick={() => selectedImg = src}
        >
          <div 
            class="absolute inset-0 bg-cover bg-center transition-transform duration-1000 group-hover:scale-105"
            style="background-image: url({src})"
          ></div>
          <div class="absolute inset-0 bg-secondary/20 group-hover:bg-transparent transition-colors duration-700"></div>
        </div>
      {/each}
    </div>
  </div>

  {#if selectedImg}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      transition:fade={{ duration: 400, easing: cubicOut }}
      class="fixed inset-0 z-50 flex items-center justify-center bg-secondary/95 backdrop-blur-md cursor-zoom-out p-8"
      onclick={() => selectedImg = null}
    >
      <img
        transition:scale={{ duration: 500, start: 0.9, easing: cubicOut }}
        src={selectedImg}
        alt="Gallery Preview"
        class="max-w-full max-h-full object-contain shadow-2xl"
      />
    </div>
  {/if}
</section>

// components/Gallery.tsx
"use client";

import React, { useState } from "react";
import { gsap } from "gsap";
import { useGSAP } from "@gsap/react";

const images = [
  { src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=2070", caption: "The room at dusk" },
  { src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2070", caption: "Handmade pasta" },
  { src: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=2070", caption: "From the sea" },
  { src: "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=2070", caption: "Garden herbs" },
  { src: "https://images.unsplash.com/photo-1551218808-94e220e084d2?q=80&w=1974", caption: "Simple linen" },
  { src: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?q=80&w=2070", caption: "Almond cake" },
];

export default function Gallery() {
  const [active, setActive] = useState<number | null>(null);

  useGSAP(() => {
    const items = document.querySelectorAll(".gallery-item");
    gsap.from(items, {
      opacity: 0,
      y: 65,
      scale: 0.985,
      duration: 1.1,
      stagger: 0.09,
      ease: "power2.out",
      scrollTrigger: {
        trigger: ".gallery-grid",
        start: "top 72%",
      },
    });
  }, []);

  const open = (index: number) => {
    setActive(index);
    const modal = document.querySelector(".gallery-modal");
    if (modal) {
      gsap.fromTo(modal, { scale: 0.96, opacity: 0 }, { scale: 1, opacity: 1, duration: 0.5, ease: "power2.out" });
    }
  };

  const close = () => {
    const modal = document.querySelector(".gallery-modal");
    if (modal) {
      gsap.to(modal, {
        scale: 0.96,
        opacity: 0,
        duration: 0.3,
        onComplete: () => setActive(null),
      });
    } else {
      setActive(null);
    }
  };

  return (
    <section id="gallery" className="section bg-[#f0e9df] py-20">
      <div className="max-w-6xl mx-auto px-6">
        <div className="mb-10">
          <span className="text-xs tracking-[3.5px] text-[#a35f3f]">IN THE HOUSE</span>
          <h4 className="serif text-[52px] tracking-tight mt-2">A quiet evening</h4>
        </div>

        <div className="gallery-grid grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {images.map((img, idx) => (
            <div 
              key={idx} 
              className="gallery-item relative aspect-[16/11] rounded-2xl overflow-hidden cursor-pointer group" 
              onClick={() => open(idx)}
            >
              <img src={img.src} alt="" className="absolute inset-0 w-full h-full object-cover transition-transform duration-1000 group-hover:scale-[1.06]" />
              <div className="absolute bottom-0 p-6 text-white text-sm bg-gradient-to-t from-black/70 w-full">
                {img.caption}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* GSAP Modal */}
      {active !== null && (
        <div className="fixed inset-0 z-[130] bg-black/90 flex items-center justify-center p-5" onClick={close}>
          <div className="gallery-modal max-w-[1020px] w-full" onClick={e => e.stopPropagation()}>
            <img src={images[active].src} alt="" className="w-full max-h-[83vh] object-contain rounded-2xl shadow-2xl" />
            <p className="text-center text-white/70 mt-5 text-xs tracking-widest">{images[active].caption}</p>
          </div>
        </div>
      )}
    </section>
  );
}
